name: color_juggler
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.9.2
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  pubspec_dependency_sorter: ^1.0.5
  solid_lints: ^0.3.1
flutter:
  uses-material-design: true
